name: SSH Build & Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enable manually starting a build, with optional input parameters
    inputs:
      debug_enabled:
        type: boolean
        description: 'Start an SSH debug session as the last step of the build'
        required: false
        default: false

permissions:
  contents: read
  actions: read
  checks: write # Required by test-reporter

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest]

    name: Build SSH on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      # On the Mac build machines, openssl v3 is installed but
      # dylibs are not linked in a path that can be found by .NET.
      - name: Link libssl on Mac OS
        run: |
          sudo mkdir -p /usr/local/lib
          export OPENSSL3_VERSION=$(brew list --versions openssl@3 | head -n 1 | sed "s/.* //")
          sudo ln -sfn $(brew --prefix)/Cellar/openssl\@3/$OPENSSL3_VERSION/lib/libssl.3.dylib /usr/local/lib/libssl.3.dylib
          sudo ln -sfn $(brew --prefix)/Cellar/openssl\@3/$OPENSSL3_VERSION/lib/libcrypto.3.dylib /usr/local/lib/libcrypto.3.dylib
        if: matrix.os == 'macOS-latest'

      - name: Install dotnet versions
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: |
            8.0.x

      - name: Use global.json dotnet version
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          global-json-file: global.json

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20.x'

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: '1.21'

      - name: Restore npm packages
        run: npm install

      - name: Restore dotnet packages
        run: dotnet restore

      - name: Build TypeScript packages
        run: npm run build-ts -- --release

      - name: Build dotnet packages
        run: dotnet build -c Release --no-restore

      - name: Build Go
        run: npm run build-go

      - name: Pack TypeScript packages
        run: npm run pack-ts

      - name: Pack dotnet packages
        run: dotnet pack -c Release --no-restore

      - name: Test TypeScript
        run: npm run test-ts
        continue-on-error: true

      - name: Test .NET 8
        run: npm run test-cs -- --release --serial --framework net8.0
        continue-on-error: true

      - name: Test .NET Framework 4.8
        if: matrix.os == 'windows-latest'
        run: npm run test-cs -- --release --serial --framework net48
        continue-on-error: true

      - name: Test Go
        run: npm run test-go -- --race
        continue-on-error: true

      - name: E2E tests
        run: ./test/e2e/e2e-validate.sh
        if: matrix.os == 'macOS-latest'
        continue-on-error: true

      - name: Start SSH debug session
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
            limit-access-to-actor: true

      - name: Publish test results
        uses: dorny/test-reporter@d61b558e8df85cb60d09ca3e5b09653b4477cea7 # v1
        with:
          name: Test SSH on ${{ matrix.os }}
          path: out/TestResults/*.trx
          reporter: dotnet-trx
